import pyautogui as p
import time
doc_name = input("Enter a name for the file: ")
doc_content = input("Enter the content for the file:\n")
time.sleep(2)
p.press('win')
time.sleep(2)
p.write("word")
time.sleep(2)
p.press('enter')
time.sleep(4)
p.press('enter')
time.sleep(2)
p.write(doc_content)
time.sleep(2)
p.hotkey('ctrl' , 's')
time.sleep(2)
p.write(doc_name)
time.sleep(2)
p.hotkey('enter')